### ISSUE TITLE
Ondersteuning voor hydra console

### ISSUE THREAD

**Issue by brechtvdv** [brechtvdv/generic-api-oslo#4]
https://www.markus-lanthaler.com/hydra/console/

**Comment by rubensworks** [comment]
Alright, implementation is finished.
But for some reason, it's not working on the Hydra console.
The only error you get is `Loading the documentation failed.`, which doesn't help much...

It's is working here though: https://alcaeus.hydra.how/

**Comment by rubensworks** [comment]
Ah, seems to work now, was indeed a caching issue
